#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

################ Autostart #################

# Load vmware settings
vmware-user-suid-wrapper &

# Set wallpaper
nitrogen --restore &

# default cursor
xsetroot -cursor_name left_ptr &

# compositor
# picom -f --experimental-backends &
picom -f --experimental-backends &
# picom -f &

# Polybar
polybar -r example &

[ "$1" = 0 ] && wmname LG3D

############### Configuration ###############
bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap           5

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a firefox desktop="^2"
# bspc rule -a Code desktop="^2"
