#!/bin/sh
exec tail -n +3 $0

# Example file to add an linux distro entry in the grub menu
# Replace "00" of the file name with the corresponding number in order to place it correctly in the generated config
# Replace "linux" of the file name with the name of the distro (Optional)

menuentry "Fedora" --class fedora --class gnu-linux --class gnu --class os $menuentry_id_option 'fedora-UUID-HERE' {
        insmod chain
        insmod fat
        search --no-floppy --fs-uuid --set=root UUID-HERE #Replace with the UUID of the partition
        chainloader /EFI/fedora/grubx64.efi
}
