#!/usr/bin/env bash

set -e          # Abort on nonzero exit status
set -u          # Abort on unbound variable
set -o pipefail # Do not hide errors within pipes

source ./settings.sh

declare -a configs
declare -r PROFILE="${1:-}" && shift || true
declare -r MODULE_SUFFIX="-sudo" # Suffix to run module as sudo
declare -r CONFIG_FILE="$(mktemp --suffix="${CONFIG_SUFFIX}")"
declare -r CONFIG_FILE_SUDO="$(mktemp --suffix="${CONFIG_SUFFIX}")"
declare -r CMD=("${DOTBOT_BIN}" -d "${BASE_DIR}" -c)
declare -i sudo_count=0

if [[ -z "${PROFILE}" ]]; then
    exception "Missing profile." 22
fi

if [[ ! -r "${PROFILES_DIR}/${PROFILE}" ]]; then
    exception "Profile \"${PROFILE}\" does not exists or it's not readable." 2
fi

cd "${BASE_DIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

while read -r line || [[ -n "${line}" ]]; do
    [[ -n "${line}" ]] && configs+=("${line}")
done < "${PROFILES_DIR}/${PROFILE}"

# Append defaults.yaml and base.yaml files
{
    echo -E "$(<"${DEFAULTS_CONFIG}")";
    echo -E "$(<"${BASE_CONFIG}")";
} > "${CONFIG_FILE}"
echo -E "$(<"${DEFAULTS_CONFIG}")" > "${CONFIG_FILE_SUDO}"

for config in "${configs[@]}" "${@}"; do
    configFile="${CONFIG_FILE}"
    module="${config%"${MODULE_SUFFIX}"}"
    module_dir="${MODULES_DIR}/${module}${CONFIG_SUFFIX}"

    if [[ ! -r "${module_dir}" ]]; then
        exception "Module \"${module}\" does not exists or it's not readable in: \"${module_dir}\"." 2
    fi

    if [[ "${config}" == *"${MODULE_SUFFIX}" ]]; then
        configFile="${CONFIG_FILE_SUDO}"
        ((sudo_count+=1))
    fi

    echo -E "$(config_message "${module}")" >> "${configFile}"
    echo -E "$(<"${module_dir}")" >> "${configFile}"
done

# Execute dotbot
cmd=("${CMD[@]}" "${CONFIG_FILE}") && "${cmd[@]}"

# Execute dotbot with sudo if any module was added
if (( sudo_count > 0 )); then
    echo -e "${LF}${LF}${LF}Executing sudo modules..."
    cmd_sudo=(sudo DOTFILES_DIR=${DOTFILES_DIR} "${CMD[@]}" "${CONFIG_FILE_SUDO}") && "${cmd_sudo[@]}"
fi

cd "${BASE_DIR}"

echo "Restart your terminal..."
