- link:
    ~/.config/zsh/.zshenv: ${DOTFILES_DIR}/zsh/.zshenv
    ~/.config/zsh/.zshrc: ${DOTFILES_DIR}/zsh/.zshrc
    ~/.config/zsh/:
        glob: true
        path: ${DOTFILES_DIR}/zsh/*

- shell:
    -
        description: Adding ZDOTDIR variable to /etc/security/pam_env.conf
        command: >-
            sudo sed -i \
                -e '/^ZDOTDIR.*/{s//ZDOTDIR     DEFAULT=@{HOME}\/.config\/zsh/;:a;n;ba;q}' \
                -e '$a\\n# ZSH Directory\nZDOTDIR     DEFAULT=@{HOME}/.config/zsh' \
                /etc/security/pam_env.conf
        quiet: true
