[bar.main]
capsule = false
capsule_radius = 10.0
capsule_opacity = 0.5
capsule_padding = 10.0
margin_edge = 0
margin_ends = 0
padding = 10
radius = 0
background_opacity = 0.0
shadow = false
widget_spacing = 10
capsule_groups = [ "system-monitoring", "system-settings" ]
start = [ "cpu", "temp", "ram", "media", "lock_keys" ]
center = [ "workspaces" ]
end = [
    "tray",
    "network",
    "bluetooth",
    "battery",
    "volume",
    "keyboard_layout",
    "clock",
    "notifications",
]

[theme]
builtin = "Tokyo-Night"

[wallpaper]
directory = "~/Pictures/Wallpapers/"
enabled = true

[backdrop]
enabled = true
tint_intensity = 0.40

[osd]
orientation = "vertical"
position = "center_right"

[shell]
settings_show_advanced = true
clipboard_auto_paste = "auto"
polkit_agent = true
show_location = false
telemetry_enabled = true

[shell.panel]
open_near_click_control_center = true
transparency_mode = "glass"
control_center_placement = "floating"
session_placement = "centered"
wallpaper_placement = "centered"

[notification]
position = "bottom_right"

[widget.tray]
drawer = true
drawer_columns = 4

[brightness]
enable_ddcutil = true

[widget.clock]
format = "{:%-I:%M %P}\n{:%d/%m/%Y}"

[widget.lock_keys]
anchor = false
display = "full"
hide_when_off = true
show_num_lock = false

[widget.network]
capsule_group = "system-settings"
show_label = false

[widget.bluetooth]
capsule_group = "system-settings"

[widget.brightness]
capsule_group = "system-settings"
show_label = false

[widget.battery]
capsule_group = "system-settings"
display_mode = "graphic"
hide_when_full = true
show_label = false

[widget.volume]
capsule_group = "system-settings"
show_label = false

[widget.cpu]
capsule_group = "system-monitoring"

[widget.ram]
capsule_group = "system-monitoring"

[widget.temp]
capsule_group = "system-monitoring"

[widget.media]
title_scroll = "on_hover"
hide_when_no_media = true

[widget.keyboard_layout]
display = "full"
show_label = false
