- link:
    $LOCALAPPDATA/Packages/Microsoft.WindowsTerminal_8wekyb3d8bbwe/LocalState/settings.json: ${DOTFILES_DIR}/windows/terminal/settings.json
    $LOCALAPPDATA/Packages/Microsoft.WindowsTerminalPreview_8wekyb3d8bbwe/LocalState/settings.json: ${DOTFILES_DIR}/windows/terminal/settings-preview.json
